title: Стиль оформления библиографии
description: Здесь Вы можете скачать стиль оформления библиографии для Citavi 6, разработанный для стран восточной европы, в которых распространен ГОСТ 7.1-2003
show_downloads: True
theme: jekyll-theme-minimal
